const actionType = {
    SEARCH_REPOSITORY: 'SEARCH_REPOSITORY',
    SET_USER: 'SET_USER',
    DRAW_CHANGE: 'DRAW_CHANGE',
    TOTAL_COUNT: 'TOTAL_COUNT',
    CURRENT_PAGE: 'CURRENT_PAGE',
    SET_ITEM: 'SET_ITEM'
}

export default actionType